# Gateway config
http_port=8080
udp_port=6000
discovery_interval_ms=3000
device_timeout_ms=10000
alarm_threshold=10
default_load=30
default_dev_name=VirtualDevice
log_file=log/history.log
config_file=config/config.conf
